# Исследование информации о компьютерных играх в 2000-2013гг.

- Автор: Севрюкова В.Ю.
- Дата:

### Цели и задачи проекта
 В этой тетрадке используем датасет /datasets/new_games.csv, который содержит информацию о продажах игр разных жанров и платформ, а также пользовательские и экспертные оценки игр.
 
 Задача — познакомиться с данными, проверить их корректность и провести предобработку, получив необходимый срез данных.
 
  В статье-исследовании хотят сделать обзор игровых платформ, изучить объёмы продаж игр разных жанров и региональные предпочтения игроков. Акцент хотят сделать на играх жанра RPG — так называют компьютерные ролевые игры, в которых игроки управляют персонажами.

### Описание данных
Данные /datasets/new_games.csv содержат информацию о продажах игр разных жанров и платформ, а также пользовательские и экспертные оценки игр:
* Name — название игры.
* Platform — название платформы.
* Year of Release — год выпуска игры.
* Genre — жанр игры.
* NA sales — продажи в Северной Америке (в миллионах проданных копий).
* EU sales — продажи в Европе (в миллионах проданных копий).
* JP sales — продажи в Японии (в миллионах проданных копий).
* Other sales — продажи в других странах (в миллионах проданных копий).
* Critic Score — оценка критиков (от 0 до 100).
* User Score — оценка пользователей (от 0 до 10).
* Rating — рейтинг организации ESRB (англ. Entertainment Software Rating Board). Эта ассоциация определяет рейтинг компьютерных игр и присваивает им подходящую возрастную категорию.

### Содержимое проекта

1. Отбор данных по времени выхода игры.
2. Категоризация игры по оценкам пользователей и экспертов.
3. Определение топ-7 платформ по количеству игр, выпущенных за весь требуемый период.

---

## 1. Загрузка данных и знакомство с ними

In [1]:
# Импортируем библиотеку pandas
import pandas as pd

In [2]:
# Выгружаем данные из датасета new_games.csv в датафрейм games
games = pd.read_csv('https://code.s3.yandex.net//datasets/new_games.csv')

In [3]:
display(games.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16956 entries, 0 to 16955
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16954 non-null  object
 1   Platform         16956 non-null  object
 2   Year of Release  16681 non-null  float64
 3   Genre            16954 non-null  object
 4   NA sales         16956 non-null  float64
 5   EU sales         16956 non-null  object
 6   JP sales         16956 non-null  object
 7   Other sales      16956 non-null  float64
 8   Critic Score     8242 non-null   float64
 9   User Score       10152 non-null  object
 10  Rating           10085 non-null  object
dtypes: float64(4), object(7)
memory usage: 1.4+ MB

None

In [4]:
display(games.head())

,Name,Platform,Year of Release,Genre,NA sales,EU sales,JP sales,Other sales,Critic Score,User Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN

Датасет /datasets/new_games.csv содержит 11 столбцов и 16956 строк, в которых представлена информация о компьютерных играх, объем данных составляет 1.4+МБ.


Изучим типы данных и их корректность:

- **Числовые значения с плавающей запятой (float64).**Четыре столбца:`Year of Release`(содержит год выпуска игры),'NA sales'(содержит информацию о продажах в Северной Америке (в миллионах проданных копий)),'Other sales'(содержит информацию о продажах в других странах (в миллионах проданных копий)),'Critic Score'(содержит оценка критиков (от 0 до 100)), и представлены типом `float64`. 


-  **Строковые данные (object).** Семь столбцов имеют тип данных `object`: `Name`(содержит информацию о названии игры), 'Platform '(содержит информацию о названии платформы),'Genre'(содержит информацию о жанре игры),'EU sales'(содержит информацию о продажах в Европе (в миллионах проданных копий)),'JP sales'(содержит информацию о продажах в Японии (в миллионах проданных копий)),'User Score'(содержит информацию об  оценках пользователей (от 0 до 10)),'Rating'(содержит информацию о рейтинге организации ESRB)-тип данных `object`.


Пропуски встречаются в шести столбцах, за исключением 'Platform','NA sales','EU sales','JP sales','Other sales'.   
После анализа типов данных видно, что часть столбцов, представленных типом `float64`, не совсем корректно, учитывая названия и содержание столбцов. Для оптимизации можно использовать целочисленные типы с уменьшенной разрядностью в тип `datetime64`.

---

## 2.  Проверка ошибок в данных и их предобработка


### 2.1. Названия, или метки, столбцов датафрейма

In [5]:
# Выводим названия всех столбцов
print("Названия столбцов датафрейма:")
print(games.columns.tolist())

Названия столбцов датафрейма:
['Name', 'Platform', 'Year of Release', 'Genre', 'NA sales', 'EU sales', 'JP sales', 'Other sales', 'Critic Score', 'User Score', 'Rating']

In [6]:
# Смотрим типы данных
games.dtypes

Name                object
Platform            object
Year of Release    float64
Genre               object
NA sales           float64
EU sales            object
JP sales            object
Other sales        float64
Critic Score       float64
User Score          object
Rating              object
dtype: object

In [7]:
# Приводим названия столбцов к змеиному стилю
games.columns = games.columns.str.lower().str.replace(' ', '_')
games.columns

Index(['name', 'platform', 'year_of_release', 'genre', 'na_sales', 'eu_sales',
       'jp_sales', 'other_sales', 'critic_score', 'user_score', 'rating'],
      dtype='object')

In [8]:
display(games)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
16951,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,0.00,0.0,0.01,0.00,NaN,NaN,NaN
16952,LMA Manager 2007,X360,2006.0,Sports,0.00,0.01,0.0,0.00,NaN,NaN,NaN
16953,Haitaka no Psychedelica,PSV,2016.0,Adventure,0.00,0.0,0.01,0.00,NaN,NaN,NaN
16954,Spirits & Spells,GBA,2003.0,Platform,0.01,0.0,0.0,0.00,NaN,NaN,NaN
16955,Winning Post 8 2016,PSV,2016.0,Simulation,0.00,0.0,0.01,0.00,NaN,NaN,NaN

### 2.2. Типы данных

In [9]:
# Опередлим тип данных всех столбцов
games.dtypes

name                object
platform            object
year_of_release    float64
genre               object
na_sales           float64
eu_sales            object
jp_sales            object
other_sales        float64
critic_score       float64
user_score          object
rating              object
dtype: object

In [10]:
# Определим уникальные значения во всех столбцах
for column in games.columns:
    print(f"Столбец: {column}")
    print(f"Уникальные значения: {games[column].unique()}")
    print("-" * 40)

Столбец: name
Уникальные значения: ['Wii Sports' 'Super Mario Bros.' 'Mario Kart Wii' ...
 'Woody Woodpecker in Crazy Castle 5' 'LMA Manager 2007'
 'Haitaka no Psychedelica']
----------------------------------------
Столбец: platform
Уникальные значения: ['Wii' 'NES' 'GB' 'DS' 'X360' 'PS3' 'PS2' 'SNES' 'GBA' 'PS4' '3DS' 'N64'
 'PS' 'XB' 'PC' '2600' 'PSP' 'XOne' 'WiiU' 'GC' 'GEN' 'DC' 'PSV' 'SAT'
 'SCD' 'WS' 'NG' 'TG16' '3DO' 'GG' 'PCFX']
----------------------------------------
Столбец: year_of_release
Уникальные значения: [2006. 1985. 2008. 2009. 1996. 1989. 1984. 2005. 1999. 2007. 2010. 2013.
 2004. 1990. 1988. 2002. 2001. 2011. 1998. 2015. 2012. 2014. 1992. 1997.
 1993. 1994. 1982. 2016. 2003. 1986. 2000.   nan 1995. 1991. 1981. 1987.
 1980. 1983.]
----------------------------------------
Столбец: genre
Уникальные значения: ['Sports' 'Platform' 'Racing' 'Role-Playing' 'Puzzle' 'Misc' 'Shooter'
 'Simulation' 'Action' 'Fighting' 'Adventure' 'Strategy' nan 'MISC'
 'ROLE-PLAYING' 'RACING' 'ACTION' 'SHOOTER' 'FIGHTING' 'SPORTS' 'PLATFORM'
 'ADVENTURE' 'SIMULATION' 'PUZZLE' 'STRATEGY']
----------------------------------------
Столбец: na_sales
Уникальные значения: [4.136e+01 2.908e+01 1.568e+01 1.561e+01 1.127e+01 2.320e+01 1.128e+01
 1.396e+01 1.444e+01 2.693e+01 9.050e+00 9.710e+00 9.000e+00 8.920e+00
 1.500e+01 9.010e+00 7.020e+00 9.430e+00 1.278e+01 4.740e+00 6.380e+00
 1.083e+01 9.540e+00 9.660e+00 8.410e+00 6.060e+00 3.430e+00 5.510e+00
 6.850e+00 9.040e+00 5.890e+00 6.030e+00 9.700e+00 5.280e+00 4.990e+00
 8.250e+00 8.520e+00 5.540e+00 6.990e+00 6.620e+00 5.030e+00 5.990e+00
 3.960e+00 2.500e+00 7.970e+00 6.910e+00 4.340e+00 4.350e+00 3.010e+00
 6.160e+00 6.760e+00 4.020e+00 4.890e+00 2.960e+00 4.760e+00 5.010e+00
 6.730e+00 5.950e+00 3.660e+00 5.550e+00 7.040e+00 6.650e+00 3.880e+00
 5.800e+00 4.100e+00 5.930e+00 4.360e+00 5.700e+00 2.030e+00 4.400e+00
 5.050e+00 3.540e+00 1.120e+00 6.820e+00 1.750e+00 3.740e+00 1.060e+00
 2.790e+00 2.910e+00 9.900e-01 2.570e+00 2.990e+00 2.280e+00 7.280e+00
 2.760e+00 2.900e+00 2.810e+00 6.600e-01 3.780e+00 3.270e+00 3.560e+00
 5.390e+00 4.590e+00 4.810e+00 4.460e+00 3.480e+00 2.850e+00 2.530e+00
 2.980e+00 3.680e+00 3.150e+00 4.410e+00 4.120e+00 2.710e+00 2.930e+00
 3.230e+00 4.050e+00 4.150e+00 2.770e+00 3.450e+00 3.110e+00 8.400e-01
 1.660e+00 7.800e-01 2.640e+00 3.170e+00 4.980e+00 2.550e+00 3.640e+00
 3.700e+00 4.010e+00 2.470e+00 8.000e-02 3.920e+00 8.000e-01 2.450e+00
 4.470e+00 3.180e+00 2.630e+00 1.880e+00 2.410e+00 2.800e+00 6.300e-01
 2.260e+00 2.490e+00 3.570e+00 3.070e+00 2.970e+00 2.950e+00 2.540e+00
 3.280e+00 3.140e+00 4.700e-01 2.620e+00 3.210e+00 2.070e+00 2.730e+00
 1.850e+00 2.180e+00 1.740e+00 3.020e+00 1.620e+00 3.130e+00 1.920e+00
 3.330e+00 3.220e+00 2.300e+00 4.260e+00 9.700e-01 6.500e-01 1.210e+00
 1.090e+00 2.100e+00 2.440e+00 1.980e+00 3.810e+00 3.590e+00 1.630e+00
 1.960e+00 3.400e+00 6.100e-01 2.050e+00 1.700e+00 3.420e+00 3.360e+00
 3.490e+00 3.050e+00 1.830e+00 2.310e+00 3.980e+00 0.000e+00 2.600e+00
 1.910e+00 2.740e+00 2.830e+00 2.360e+00 1.730e+00 1.940e+00 2.290e+00
 1.820e+00 2.420e+00 3.040e+00 1.800e+00 2.080e+00 1.870e+00 4.180e+00
 3.190e+00 4.210e+00 3.630e+00 2.780e+00 2.000e-01 1.610e+00 1.540e+00
 2.520e+00 2.660e+00 1.000e-01 2.820e+00 2.190e+00 1.560e+00 3.030e+00
 2.200e+00 2.090e+00 2.110e+00 1.480e+00 4.000e+00 5.800e-01 2.510e+00
 3.000e+00 2.240e+00 1.460e+00 1.410e+00 9.200e-01 8.800e-01 1.280e+00
 2.250e+00 3.380e+00 2.040e+00 3.790e+00 4.030e+00 1.650e+00 7.100e-01
 1.420e+00 1.100e+00 2.320e+00 1.200e-01 2.350e+00 2.120e+00 1.400e+00
 1.680e+00 1.130e+00 1.220e+00 2.670e+00 1.020e+00 1.190e+00 1.530e+00
 2.150e+00 9.000e-01 1.970e+00 6.800e-01 1.160e+00 9.300e-01 1.440e+00
 1.600e-01 2.130e+00 2.210e+00 1.780e+00 8.600e-01 1.350e+00 1.050e+00
 2.230e+00 2.400e+00 1.370e+00 1.300e+00 1.950e+00 1.930e+00 1.330e+00
 1.490e+00 1.580e+00 5.000e-02 6.000e-01 2.020e+00 2.380e+00 1.600e+00
 2.010e+00 1.570e+00 1.230e+00 1.900e+00 2.140e+00 1.170e+00 2.270e+00
 1.640e+00 5.900e-01 1.550e+00 4.600e-01 8.100e-01 1.450e+00 2.700e-01
 1.470e+00 1.990e+00 1.500e+00 9.000e-02 2.610e+00 1.890e+00 5.000e-01
 8.900e-01 9.500e-01 2.340e+00 7.200e-01 1.720e+00 1.180e+00 1.760e+00
 7.300e-01 1.270e+00 2.060e+00 5.500e-01 1.520e+00 1.690e+00 2.170e+00
 5.100e-01 1.000e+00 1.290e+00 1.380e+00 1.150e+00 1.670e+00 1.360e+00
 1.010e+00 1.040e+00 1.840e+00 2.220e+00 7.900e-01 1.510e+00 1.070e+00
 1.320e+00 1.590e+00 2.000e-02 2.900e-01 1.250e+00 2.560e+00 1.430e+00
 1.200e+00 4.100e-01 2.800e-01 4.300e-01 6.900e-01 2.000e+00 7.600e-01
 1.860e+00 4.800e-01 6.200e-01 1.310e+00 3.700e-01 1.500e-01 6.400e-01
 2.600e-01 4.900e-01 1.110e+00 1.300e-01 1.810e+00 1.030e+00 1.260e+00
 8.700e-01 7.700e-01 9.600e-01 1.390e+00 1.080e+00 8.500e-01 9.100e-01
 3.000e-01 3.800e-01 9.400e-01 7.000e-02 1.340e+00 1.240e+00 3.400e-01
 1.400e-01 1.000e-02 5.200e-01 8.200e-01 8.300e-01 1.100e-01 2.500e-01
 1.770e+00 3.600e-01 7.500e-01 7.400e-01 1.800e-01 2.200e-01 5.300e-01
 4.200e-01 3.200e-01 3.900e-01 2.400e-01 2.300e-01 6.000e-02 4.500e-01
 7.000e-01 6.700e-01 3.500e-01 5.600e-01 1.140e+00 9.800e-01 5.700e-01
 5.400e-01 4.000e-02 1.700e-01 4.400e-01 3.000e-02 3.300e-01 3.100e-01
 4.000e-01 2.100e-01 1.900e-01]
----------------------------------------
Столбец: eu_sales
Уникальные значения: ['28.96' '3.58' '12.76' '10.93' '8.89' '2.26' '9.14' '9.18' '6.94' '0.63'
 '10.95' '7.47' '6.18' '8.03' '4.89' '8.49' '9.09' '0.4' '3.75' '9.2'
 '4.46' '2.71' '3.44' '5.14' '5.49' '3.9' '5.35' '3.17' '5.09' '4.24'
 '5.04' '5.86' '3.68' '4.19' '5.73' '3.59' '4.51' '2.55' '4.02' '4.37'
 '6.31' '3.45' '2.81' '2.85' '3.49' '0.01' '3.35' '2.04' '3.07' '3.87'
 '3.0' '4.82' '3.64' '2.15' '3.69' '2.65' '2.56' '3.11' '3.14' '1.94'
 '1.95' '2.47' '2.28' '3.42' '3.63' '2.36' '1.71' '1.85' '2.79' '1.24'
 '6.12' '1.53' '3.47' '2.24' '5.01' '2.01' '1.72' '2.07' '6.42' '3.86'
 '0.45' '3.48' '1.89' '5.75' '2.17' '1.37' '2.35' '1.18' '2.11' '1.88'
 '2.83' '2.99' '2.89' '3.27' '2.22' '2.14' '1.45' '1.75' '1.04' '1.77'
 '3.02' '2.75' '2.16' '1.9' '2.59' '2.2' '4.3' '0.93' '2.53' '2.52' '1.79'
 '1.3' '2.6' '1.58' '1.2' '1.56' '1.34' '1.26' '0.83' '6.21' '2.8' '1.59'
 '1.73' '4.33' '1.83' '0.0' '2.18' '1.98' '1.47' '0.67' '1.55' '1.91'
 '0.69' '0.6' '1.93' '1.64' '0.55' '2.19' '1.11' '2.29' '2.5' '0.96'
 '1.21' '1.12' '0.77' '1.69' '1.08' '0.79' '2.37' '2.46' '0.26' '0.75'
 '1.25' '2.43' '0.98' '0.74' '2.23' '0.61' '2.45' '1.41' '1.8' '3.28'
 '1.16' '1.99' '1.38' '1.36' '1.17' '1.19' '0.99' '1.68' '2.0' '1.33'
 '1.57' '1.48' '2.1' '1.27' '1.97' '0.91' '1.39' '1.96' '0.24' '1.51'
 '0.14' '1.29' '2.39' '1.03' '0.5' '0.58' '1.31' '2.02' '1.32' '1.01'
 '2.27' '2.3' '1.82' '2.78' '0.44' '0.48' '0.27' '0.21' '2.48' '0.51'
 '1.52' '0.04' '0.28' '1.35' '0.87' '2.13' '1.13' '1.76' '0.76' '2.12'
 '0.66' '1.6' '1.44' '1.43' '1.7' '0.47' '1.87' '0.86' '0.73' '1.28'
 '0.81' '1.09' '0.68' '1.22' '1.4' '1.02' '1.49' '1.14' '0.49' '0.9'
 '0.38' '1.42' '0.95' '1.62' '0.71' '1.05' '0.92' '0.33' '0.3' '1.67'
 '1.0' '0.89' '0.1' '0.72' '0.59' '0.56' '0.16' '0.97' '0.62' 'unknown'
 '0.85' '0.94' '0.88' '0.84' '1.06' '0.2' '1.15' '0.8' '1.1' '0.7' '1.92'
 '0.32' '0.15' '0.53' '0.09' '1.46' '0.29' '0.22' '1.23' '0.07' '0.17'
 '0.54' '0.36' '0.31' '1.84' '0.52' '0.11' '0.64' '0.12' '2.05' '1.63'
 '0.82' '0.08' '0.57' '1.65' '0.19' '0.02' '0.43' '0.25' '1.5' '0.18'
 '0.39' '0.13' '1.07' '0.46' '0.41' '0.06' '0.03' '0.37' '0.05' '0.23'
 '0.65' '0.42' '0.34' '0.35' '0.78']
----------------------------------------
Столбец: jp_sales
Уникальные значения: ['3.77' '6.81' '3.79' '3.28' '10.22' '4.22' '6.5' '2.93' '4.7' '0.28'
 '1.93' '4.13' '7.2' '3.6' '0.24' '2.53' '0.98' '0.41' '3.54' '4.16'
 '6.04' '4.18' '3.84' '0.06' '0.47' '5.38' '5.32' '5.65' '1.87' '0.13'
 '3.12' '0.36' '0.11' '4.35' '0.65' '0.07' '0.08' '0.49' '0.3' '2.66'
 '2.69' '0.48' '0.38' '5.33' '1.91' '3.96' '3.1' '1.1' '1.2' '0.14' '2.54'
 '2.14' '0.81' '2.12' '0.44' '3.15' '1.25' '0.04' '0.0' '2.47' '2.23'
 '1.69' '0.01' '3.0' '0.02' '4.39' '1.98' '0.1' '3.81' '0.05' '2.49'
 '1.58' '3.14' '2.73' '0.66' '0.22' '3.63' '1.45' '1.31' '2.43' '0.7'
 '0.35' '1.4' '0.6' '2.26' '1.42' '1.28' '1.39' '0.87' '0.17' '0.94'
 '0.19' '0.21' '1.6' '0.16' '1.03' '0.25' '2.06' '1.49' '1.29' '0.09'
 '2.87' '0.03' '0.78' '0.83' '2.33' '2.02' '1.36' '1.81' '1.97' '0.91'
 '0.99' '0.95' '2.0' '1.01' '2.78' '2.11' '1.09' '0.2' '1.9' '1.27' '3.61'
 '1.57' '2.2' '1.7' '1.08' '0.15' '1.11' '0.29' '1.54' '0.12' '0.89'
 '4.87' '1.52' '1.32' '1.15' '4.1' '1.46' '0.46' '1.05' '1.61' '0.26'
 '1.38' '0.62' '0.73' '0.57' '0.31' '0.58' '1.76' '2.1' '0.9' '0.51'
 '0.64' '2.46' '0.23' '0.37' '0.92' '1.07' '2.62' '1.12' '0.54' '0.27'
 '0.59' '3.67' '0.55' '1.75' '3.44' '0.33' '2.55' '2.32' '2.79' '0.74'
 '3.18' '0.82' '0.77' '0.4' '2.35' '3.19' '0.8' '0.76' '3.03' '0.88'
 'unknown' '0.45' '1.16' '0.34' '1.19' '1.13' '2.13' '1.96' '0.71' '1.04'
 '2.68' '0.68' '2.65' '0.96' '2.41' '0.52' '0.18' '1.34' '1.48' '2.34'
 '1.06' '1.21' '2.29' '1.63' '2.05' '2.17' '1.56' '1.35' '1.33' '0.63'
 '0.79' '0.75' '0.53' '1.53' '1.3' '0.39' '0.69' '0.42' '0.93' '0.56'
 '0.84' '0.72' '0.32' '1.71' '1.65' '0.61' '1.51' '1.5' '1.44' '1.24'
 '1.18' '1.37' '1.0' '1.26' '0.85' '0.43' '0.67' '1.14' '0.86' '1.17'
 '0.5' '1.02' '0.97']
----------------------------------------
Столбец: other_sales
Уникальные значения: [8.450e+00 7.700e-01 3.290e+00 2.950e+00 1.000e+00 5.800e-01 2.880e+00
 2.840e+00 2.240e+00 4.700e-01 2.740e+00 1.900e+00 7.100e-01 2.150e+00
 1.690e+00 1.770e+00 3.960e+00 1.057e+01 5.500e-01 2.040e+00 1.360e+00
 4.200e-01 4.600e-01 1.410e+00 1.780e+00 5.000e-01 1.180e+00 8.000e-01
 1.160e+00 1.320e+00 5.900e-01 2.380e+00 1.130e+00 7.800e-01 2.420e+00
 1.120e+00 1.280e+00 1.570e+00 1.300e+00 1.010e+00 9.100e-01 1.790e+00
 1.970e+00 8.600e-01 1.210e+00 2.300e-01 7.600e-01 7.400e-01 7.530e+00
 2.900e-01 1.030e+00 5.200e-01 2.110e+00 1.600e+00 1.610e+00 3.500e-01
 9.700e-01 1.060e+00 6.300e-01 1.500e-01 7.900e-01 9.600e-01 1.250e+00
 9.000e-01 8.100e-01 3.900e-01 6.800e-01 8.500e-01 1.800e-01 8.000e-02
 6.700e-01 7.000e-01 4.100e-01 3.300e-01 6.000e-01 5.400e-01 1.730e+00
 1.230e+00 1.600e-01 1.110e+00 3.100e-01 4.800e-01 6.200e-01 1.900e-01
 6.900e-01 1.020e+00 7.300e-01 1.080e+00 4.500e-01 2.800e-01 5.100e-01
 2.200e-01 1.090e+00 9.900e-01 3.000e-01 6.400e-01 6.600e-01 9.800e-01
 1.390e+00 1.400e-01 1.370e+00 7.000e-02 2.100e-01 6.100e-01 1.700e-01
 1.200e-01 0.000e+00 7.200e-01 2.400e-01 8.200e-01 1.740e+00 8.700e-01
 9.200e-01 5.700e-01 1.100e-01 4.000e-02 5.600e-01 2.000e-01 3.400e-01
 9.000e-02 8.300e-01 4.400e-01 6.000e-02 3.200e-01 3.800e-01 1.480e+00
 3.700e-01 1.000e-01 2.500e-01 3.600e-01 1.300e-01 4.300e-01 5.000e-02
 2.000e-02 2.600e-01 4.000e-01 7.500e-01 1.930e+00 8.400e-01 5.300e-01
 8.900e-01 1.670e+00 2.700e-01 2.930e+00 4.900e-01 1.000e-02 2.460e+00
 3.000e-02 1.510e+00 2.050e+00 1.680e+00 1.820e+00 1.330e+00 9.400e-01
 9.300e-01]
----------------------------------------
Столбец: critic_score
Уникальные значения: [76. nan 82. 80. 89. 58. 87. 91. 61. 97. 95. 77. 88. 83. 94. 93. 85. 86.
 98. 96. 90. 84. 73. 74. 78. 92. 71. 72. 68. 62. 49. 67. 81. 66. 56. 79.
 70. 59. 64. 75. 60. 63. 69. 50. 25. 42. 44. 55. 48. 57. 29. 47. 65. 54.
 20. 53. 37. 38. 33. 52. 30. 32. 43. 45. 51. 40. 46. 39. 34. 35. 41. 36.
 28. 31. 27. 26. 19. 23. 24. 21. 17. 22. 13.]
----------------------------------------
Столбец: user_score
Уникальные значения: ['8' nan '8.3' '8.5' '6.6' '8.4' '8.6' '7.7' '6.3' '7.4' '8.2' '9' '7.9'
 '8.1' '8.7' '7.1' '3.4' '5.3' '4.8' '3.2' '8.9' '6.4' '7.8' '7.5' '2.6'
 '7.2' '9.2' '7' '7.3' '4.3' '7.6' '5.7' '5' '9.1' '6.5' 'tbd' '8.8' '6.9'
 '9.4' '6.8' '6.1' '6.7' '5.4' '4' '4.9' '4.5' '9.3' '6.2' '4.2' '6' '3.7'
 '4.1' '5.8' '5.6' '5.5' '4.4' '4.6' '5.9' '3.9' '3.1' '2.9' '5.2' '3.3'
 '4.7' '5.1' '3.5' '2.5' '1.9' '3' '2.7' '2.2' '2' '9.5' '2.1' '3.6' '2.8'
 '1.8' '3.8' '0' '1.6' '9.6' '2.4' '1.7' '1.1' '0.3' '1.5' '0.7' '1.2'
 '2.3' '0.5' '1.3' '0.2' '0.6' '1.4' '0.9' '1' '9.7']
----------------------------------------
Столбец: rating
Уникальные значения: ['E' nan 'M' 'T' 'E10+' 'K-A' 'AO' 'EC' 'RP']
----------------------------------------

Возможные причины некорртектных типов данных:
- Наличие пропусков (NaN, пустые строки, специальные метки).
Значения типа 'N/A', 'NULL', '' (пустая строка) не распознаются как числа. При преобразовании они становятся NaN.
- Строковые значения в числовых столбцах. 
В числовом столбце могут быть значения вроде '1 000', '1,234.56', '1000 USD'. Запятые, пробелы, валюта мешают преобразованию в число.
- Смешанные типы в одном столбце.
Например, часть строк — числа, часть — текст ('123', 'error', '456'). Pandas сохраняет весь столбец как object (строковый тип).
- Нестандартные разделители.
В некоторых данных десятичный разделитель — запятая (,), а не точка (.), либо используются разные форматы чисел.
- Опечатки и мусорные данные.
Случайно попавшие символы ('123abc', 'nan', 'NULL'), лишние пробелы.

In [11]:
# Опередлим тип данных всех столбцов
games.dtypes

name                object
platform            object
year_of_release    float64
genre               object
na_sales           float64
eu_sales            object
jp_sales            object
other_sales        float64
critic_score       float64
user_score          object
rating              object
dtype: object

In [12]:
# Перечень столбцов, которые должны быть числовыми
numeric_columns = ['year_of_release','na_sales','eu_sales','jp_sales','other_sales','critic_score','user_score']

In [13]:
# Преобразование типов данных на числовые и замена всех значений на NaN, которые не удалось преобразовать в число
for col in numeric_columns:
    games[col] = pd.to_numeric(games[col],errors='coerce')

In [14]:
games.dtypes

name                object
platform            object
year_of_release    float64
genre               object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
critic_score       float64
user_score         float64
rating              object
dtype: object

### 2.3. Наличие пропусков в данных

In [15]:
# Находим количество пропусков в каждом столбце в абсолютном значении
count = games.isna().sum()
count

name                  2
platform              0
year_of_release     275
genre                 2
na_sales              0
eu_sales              6
jp_sales              4
other_sales           0
critic_score       8714
user_score         9268
rating             6871
dtype: int64

In [16]:
# Подсчёт процента пропусков
count_= (games.isna().sum() / len(games)) * 100
count_

name                0.011795
platform            0.000000
year_of_release     1.621845
genre               0.011795
na_sales            0.000000
eu_sales            0.035386
jp_sales            0.023590
other_sales         0.000000
critic_score       51.391838
user_score         54.659118
rating             40.522529
dtype: float64

Вывод: большое количество пропусков встречается в столбцах 'Critic Score'(51%),'User Score'(55%),'Rating'(41%).
Пропуски в данных могут возникать по разным причинам: 
- данные не были введены или зарегистрированы; 
- ошибки при сборе или передаче данных; 
- несовместимость форматов данных при объединении различных источников; 
- преднамеренное удаление данных из-за их недостоверности или неактуальности. 

Пропуски можно пропустить, удалить или самостоятельно запонить.

In [17]:
# Замена пропусков в столбце 'NA sales' на среднее значение
games['na_sales'] = games['na_sales'].fillna(games.groupby(['platform','year_of_release'])['na_sales'].transform('mean'))

In [18]:
display(games['na_sales'])

0        41.36
1        29.08
2        15.68
3        15.61
4        11.27
         ...
16951     0.00
16952     0.00
16953     0.00
16954     0.01
16955     0.00
Name: na_sales, Length: 16956, dtype: float64

In [19]:
# Замена пропусков в столбце 'EU sales' на среднее значение
games['eu_sales'] = games['eu_sales'].fillna(games.groupby(['platform','year_of_release'])['eu_sales'].transform('mean'))

In [20]:
display(games['eu_sales'])

0        28.96
1         3.58
2        12.76
3        10.93
4         8.89
         ...
16951     0.00
16952     0.01
16953     0.00
16954     0.00
16955     0.00
Name: eu_sales, Length: 16956, dtype: float64

In [21]:
# Замена пропусков в столбце 'JP sales' на среднее значение
games['jp_sales'] = games['jp_sales'].fillna(games.groupby(['platform', 'year_of_release'])['jp_sales'].transform('mean'))

In [22]:
display(games['jp_sales'])

0         3.77
1         6.81
2         3.79
3         3.28
4        10.22
         ...
16951     0.01
16952     0.00
16953     0.01
16954     0.00
16955     0.01
Name: jp_sales, Length: 16956, dtype: float64

In [23]:
print(f"До удаления: {len(games)} строк")
print(f"Строк с пропусками: {games.isna().any(axis=1).sum()}")

До удаления: 16956 строк
Строк с пропусками: 10045

In [24]:
# Удаление пропущенных значений в столбе
games_clean = games.dropna(subset=['name','year_of_release','genre'])

In [25]:
print(f"После удаления: {len(games_clean)} строк")
print(f"Удалено строк: {len(games) - len(games_clean)}")

После удаления: 16679 строк
Удалено строк: 277

In [26]:
display(games)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8.0,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8.0,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
16951,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,0.00,0.00,0.01,0.00,NaN,NaN,NaN
16952,LMA Manager 2007,X360,2006.0,Sports,0.00,0.01,0.00,0.00,NaN,NaN,NaN
16953,Haitaka no Psychedelica,PSV,2016.0,Adventure,0.00,0.00,0.01,0.00,NaN,NaN,NaN
16954,Spirits & Spells,GBA,2003.0,Platform,0.01,0.00,0.00,0.00,NaN,NaN,NaN
16955,Winning Post 8 2016,PSV,2016.0,Simulation,0.00,0.00,0.01,0.00,NaN,NaN,NaN

### 2.4. Явные и неявные дубликаты в данных

In [27]:
# Изучим уникальные значения с названиями жанра игры, платформы, рейтинга и года выпуска
games['genre'].unique()

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy', nan, 'MISC', 'ROLE-PLAYING', 'RACING', 'ACTION',
       'SHOOTER', 'FIGHTING', 'SPORTS', 'PLATFORM', 'ADVENTURE',
       'SIMULATION', 'PUZZLE', 'STRATEGY'], dtype=object)

In [28]:
display(games['platform'].unique())

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       'PS4', '3DS', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne',
       'WiiU', 'GC', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

In [29]:
display(games['name'].unique())

array(['Wii Sports', 'Super Mario Bros.', 'Mario Kart Wii', ...,
       'Woody Woodpecker in Crazy Castle 5', 'LMA Manager 2007',
       'Haitaka no Psychedelica'], dtype=object)

In [30]:
display(games['year_of_release'].unique())

array([2006., 1985., 2008., 2009., 1996., 1989., 1984., 2005., 1999.,
       2007., 2010., 2013., 2004., 1990., 1988., 2002., 2001., 2011.,
       1998., 2015., 2012., 2014., 1992., 1997., 1993., 1994., 1982.,
       2016., 2003., 1986., 2000.,   nan, 1995., 1991., 1981., 1987.,
       1980., 1983.])

In [31]:
# Проведем нормализацию данных, сначала приведем к нижнему регистру поля 'Genre','Name'
games['genre'].str.lower()

0              sports
1            platform
2              racing
3              sports
4        role-playing
             ...
16951          action
16952          sports
16953       adventure
16954        platform
16955      simulation
Name: genre, Length: 16956, dtype: object

In [32]:
 games['name'].str.lower()

0                           wii sports
1                    super mario bros.
2                       mario kart wii
3                    wii sports resort
4             pokemon red/pokemon blue
                     ...
16951    samurai warriors: sanada maru
16952                 lma manager 2007
16953          haitaka no psychedelica
16954                 spirits & spells
16955              winning post 8 2016
Name: name, Length: 16956, dtype: object

In [33]:
# Приведем к верхнему регистру поле 'Rating'
games['rating'].str.upper()

0          E
1        NaN
2          E
3          E
4        NaN
        ...
16951    NaN
16952    NaN
16953    NaN
16954    NaN
16955    NaN
Name: rating, Length: 16956, dtype: object

In [34]:
# Проверим наличие явных дубликатов в данных
duplicates = games[games.duplicated()]

In [35]:
# Количество дубликатов
duplicates.shape[0]

182

In [36]:
# Удалим дубликаты 
games_clean = games.drop_duplicates()

In [37]:
# Сохраняем исходную длину датафрейма
original_length = len(games)
# Считаем количество удалённых строк
removed_duplicates = original_length - len(games_clean)

print(f"Удалено дубликатов: {removed_duplicates}")

Удалено дубликатов: 182

Обнаружено 182 строки явных дубликатов. Дубликаты можно пропустить, или удалить, или заполнить (к примеру, средним значением по столбцу).

In [38]:
# Определим исходный датафрейм и его количество строк
original_df = games

In [39]:
original_count = len(original_df)

In [40]:
display(original_count)

16956

In [41]:
# Определим датафрейм, используемый после удаления дубликатов, и его количество строк
cleaned_df=original_df.drop_duplicates()

In [42]:
cleaned_count = len(cleaned_df)

In [43]:
display(cleaned_count)

16774

In [44]:
# Абсолютное количество удалённых строк
deleted_count = original_count - cleaned_count

In [45]:
display(deleted_count)

182

In [46]:
# Относительное количество удалённых строк (%)
deleted=(deleted_count/original_count-1)*100

In [47]:
display(deleted)

-98.92663364000943

В данном пункте мы определили уникальные значения в столбцах: 'Genre', 'Platform', 'Rating', 'Year of Release', и провели нормализацию в них. 
Определили явные дубликаты (их количество составило 182 строки), количество строк исходного датафрейма - 16956, количество после удаления дубликатов - 16774. В относительном значении количество удаленных строк составляет 1.073%.

---

## 3. Фильтрация данных

Коллеги хотят изучить историю продаж игр в начале XXI века, и их интересует период с 2000 по 2013 год включительно.

In [48]:
# Сохраним новый срез данных в отдельном датафрейме
df_actual = games.loc[(games['year_of_release']>=2000)&(games['year_of_release']<=2013)].copy()

In [49]:
display(df_actual)

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8.0,E
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8.0,E
6,New Super Mario Bros.,DS,2006.0,Platform,11.28,9.14,6.50,2.88,89.0,8.5,E
7,Wii Play,Wii,2006.0,Misc,13.96,9.18,2.93,2.84,58.0,6.6,E
...,...,...,...,...,...,...,...,...,...,...,...
16947,Men in Black II: Alien Escape,GC,2003.0,Shooter,0.01,0.00,0.00,0.00,NaN,NaN,T
16949,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,0.01,0.00,0.00,0.00,NaN,NaN,NaN
16950,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,0.00,0.00,0.00,0.00,NaN,NaN,NaN
16952,LMA Manager 2007,X360,2006.0,Sports,0.00,0.01,0.00,0.00,NaN,NaN,NaN
16954,Spirits & Spells,GBA,2003.0,Platform,0.01,0.00,0.00,0.00,NaN,NaN,NaN

---

## 4. Категоризация данных

In [50]:
# Создадим копию и разделим все игры по оценкам пользователей и выделим категории
df_actual = df_actual.copy()

In [51]:
def score_category(score):
    if score >= 8:
        return 'высокая оценка'
    elif score >= 3:
        return 'средняя оценка'
    else:
        return 'низкая оценка'

In [52]:
df_actual.loc[:,'user_score_group']= df_actual['user_score'].apply(score_category)

In [53]:
# Мы создали новый столбец 'user_score_group', который будет содержать 3 категориии
display(df_actual['user_score_group'])

0        высокая оценка
2        высокая оценка
3        высокая оценка
6        высокая оценка
7        средняя оценка
              ...
16947     низкая оценка
16949     низкая оценка
16950     низкая оценка
16952     низкая оценка
16954     низкая оценка
Name: user_score_group, Length: 12980, dtype: object

In [54]:
# Разделим все игры по оценкам критиков и выделим категории
def score_category(score):
    if score >= 80:
        return 'высокая оценка'
    elif score >= 30:
        return 'средняя оценка'
    else:
        return 'низкая оценка'

In [55]:
df_actual.loc[:,'user_score_group_2']= df_actual['critic_score'].apply(score_category)

In [56]:
# Мы создали новый столбец 'user_score_group_2', который будет содержать 3 категориии.
display(df_actual['user_score_group_2'])

0        средняя оценка
2        высокая оценка
3        высокая оценка
6        высокая оценка
7        средняя оценка
              ...
16947     низкая оценка
16949     низкая оценка
16950     низкая оценка
16952     низкая оценка
16954     низкая оценка
Name: user_score_group_2, Length: 12980, dtype: object

In [57]:
# Сгруппируем данные по выделенным категориям и посчитаем количество игр в каждой категории
category_counts = df_actual['user_score_group'].value_counts(dropna=False)

In [58]:
display(category_counts)

низкая оценка     6525
средняя оценка    4148
высокая оценка    2307
Name: user_score_group, dtype: int64

In [59]:
category_counts_2 = df_actual['user_score_group_2'].value_counts(dropna=False)

In [60]:
display(category_counts)

низкая оценка     6525
средняя оценка    4148
высокая оценка    2307
Name: user_score_group, dtype: int64

In [61]:
# Определим Топ-7 платформ по количеству игр, выпущенные за 2000-2013 гг.
top_7 = df_actual.groupby('platform').size().sort_values(ascending=False).head(7)

In [62]:
display(top_7)

platform
PS2     2154
DS      2146
Wii     1294
PSP     1199
X360    1138
PS3     1107
GBA      826
dtype: int64

---

## 5. Итоговый вывод

Были загружены данные /datasets/new_games.csv содержит 11 столбцов и 16956 строк, в которых представлена информация о компьютерных играх, объем данных составляет 1.4+МБ. Изучим типы данных и их корректность:

Числовые значения с плавающей запятой (float64).Четыре столбца:Year of Release(содержит год выпуска игры),'NA sales'(содержит информацию о продажах в Северной Америке (в миллионах проданных копий)),'Other sales'(содержит информацию о продажах в других странах (в миллионах проданных копий)),'Critic Score'(содержит оценка критиков (от 0 до 100)), и представлены типом float64.
Строковые данные (object). Семь столбцов имеют тип данных object: Name(содержит информацию о названии игры), 'Platform '(содержит информацию о названии платформы),'Genre'(содержит информацию о жанре игры),'EU sales'(содержит информацию о продажах в Европе (в миллионах проданных копий)),'JP sales'(содержит информацию о продажах в Японии (в миллионах проданных копий)),'User Score'(содержит информацию об оценках пользователей (от 0 до 10)),'Rating'(содержит информацию о рейтинге организации ESRB)-тип данных object.

Пропуски встречаются в шести столбцах, за исключением 'Platform','NA sales','EU sales','JP sales','Other sales'.
После анализа типов данных видно, что часть столбцов, представленных типом float64, не совсем корректно, учитывая названия и содержание столбцов. Для оптимизации можно использовать целочисленные типы с уменьшенной разрядностью в тип datetime64.

Вывод:
большое количество пропусков встречается в столбцах 'Critic Score'(51%),'User Score'(55%),'Rating'(41%). 
Для оптимизации работы с данными в датафрейме были произведены следующие изменения типов данных:
столбцы 'Year of Release','NA sales','EU sales','JP sales','Other sales','Critic Score','User Score'переведенычисловой тип данных.
Для дополнительной работы с данными были созданы дополнительные столбцы:
'count' - количество пропусков в каждом столбце в абсолютном значении,'count_'- % пропусков, 'duplicates'- список явных дубликатов, 'original_count'- количество строк, 'deleted_count'- количество удаленных строк, 'category'- категории по оценкам пользователей.
​
​
​
​